In [1]:
# 비교 연산 & 데이터 추출
    # 넘파이의 비교 연산은 배열 내, 배열 간의 비교 연산이 있음
    # 비교 연산들의 결과는 항상 불린형을 가진 배열로 추출

In [2]:
# 브로드캐스팅 비교 연산
    # 벡터 내의 전체 요소에 해당 연산이 적용
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

In [4]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [5]:
# all, any
    # all() : 배열 내의 모든 값이 True일 때만 True 반환
    # any() : 배열 내의 어떤 값 중 하나라도 True일 때 True 반환
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [6]:
(x > 3).all()

False

In [7]:
(x > 3).any()

True

In [9]:
(x < 10).all(), (x < 10).any()

(True, True)

In [10]:
(x > 10).any()

False

In [11]:
# where : 인덱스 반환 함수 => 참인 값들의 인덱스를 반환
x = np.array([4, 6, 7, 3, 2])
np.where(x > 5)

(array([1, 2], dtype=int64),)

In [12]:
# where 함수는 참인 경우와 거짓인 경우의 값을 매칭해주는ㄴ 값 지정 가능
np.where(x > 5, 10, 20)

array([20, 10, 10, 20, 20])

In [38]:
# 하나의 배열 내에서 정렬된 값의 인덱스를 반환해주는 함수
    # argsort : 배열 내의 값들을 작은 순서대로 인덱스를 반환
    # argmax : 배열 내의 값들 중 가장 큰 값의 인덱스 반환
    # argmin : 배열 내의 값들 중 가장 작은 값의 인덱스 반환
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [14]:
np.argmax(x)

2

In [15]:
np.argmin(x)

4

In [17]:
# 비교 연산과 인덱스 추출 함수를 활용해 데이터 추출
    # 대표적인 기법으로 불린 인덱스(boolean index), 팬시 인덱스(fancy index)가 있음

In [18]:
# 불린 인덱스 : 배열에 있는 값들을 특정 조건에 의해 반환할 수 있는데, 그 특정 조건을 불린형의 배열에 넣어서 추출하는 기법
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [19]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [20]:
x.shape

(5,)

In [21]:
cond.shape

(5,)

In [22]:
# 위에서 보면 x > 3의 결과를 불린형 배열의 형태로 추출 가능
    # 이렇게 생성된 배열을 기존 인덱스에 넣는다면 x[cond]처럼 불린형 배열이 참인 경우에만 값을 추출
    # 불린 인덱스는 크게 다음 두 가지 조건을 만족해야 작동
        # 인덱스에 들어가는 배열은 불린형이어야 한다.
        # 인덱스에 들어가는 불린형 배열의 구조(shape)와 추출 대상이 되는 배열의 구조는 같아야 한다.

In [23]:
# 팬시 인덱스 : 불린 인덱스와 달리 정수형 배열의 값을 사용 => 해당 정수의 인덱스에 위치한 값 반환
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [24]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [26]:
x = np.array([[1, 4], [9, 16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a, b]

array([ 1,  9,  9, 16,  4,  4])

In [40]:
# x.take((a, b)), x.take([a, b])  # take 함수는 2차원 이상에서 적용되기 애매한 듯

In [41]:
arr = np.array([[17, 27, 14, 11], [8, 24, 25, 26], [11, 26, 26, 23], [3, 30, 4, 25], [22, 18, 24, 11]])
print(arr[[0, 2, 1]])

[[17 27 14 11]
 [11 26 26 23]
 [ 8 24 25 26]]


In [43]:
arr[[0, 2, 1]] # 이중 리스트 : 인덱싱

array([[17, 27, 14, 11],
       [11, 26, 26, 23],
       [ 8, 24, 25, 26]])