In [1]:
# 넘파이의 특징
    # 일반적인 리스트보다 속도가 빠르고 효율적인 메모리 사용이 가능
    # 반복문을 사용하지 않음
    # 다른 언어와 통합 사용 가능
# 넘파이 배열
    # 파이썬의 리스트와 같이 넘파이에서 텐서 데이터를 다루는 객체
        # 텐서(tensor) : 선형대수에서 사용하는 데이터 배열
            # 데이터 배열의 랭크에 따라 별도의 용어 존재
                # Rank 0 : 스칼라, Rank 1 : 벡터, Rank 2 : 행렬, Rank n : n차원 텐서

import numpy as np

test_1 = np.array([1, 4, 5, "8"], float)
print(test_1)

# np.array에서 m * n 크기의 배열을 만들고자 할 때, 비어있는 칸이 있으면 안 됨
# 파이썬 리스트는 메모리 주소만 순서대로 나열, 넘파이 배열은 실제 값을 연속적으로 나열
    # 파이썬 리스트는 동적 메모리 할당 가능, 넘파이 배열은 동적 메모리 할당 불가능

print(type(test_1[3]))
# <class 'numpy.float64'> => 64 : 칸 당 64비트(8바이트), 32 : 칸 당 32비트(4바이트)

print(test_1.dtype)
# dtype : 배열 전체의 데이터 타입 반환

print(test_1.shape)
# shape : 배열의 구조를 튜플 형식으로 반환, rank 2 이상일 때는 (x, y, z)형식으로 반환

print(test_1.ndim, test_1. size)
# ndim : 차원의 크기 or rank, size : 해당 넘파이 배열에 있는 모든 데이터의 개수 (x * y * z)

print(np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype= int))
# dtype : dtype에 해당하는 형태로 변환

import sys
print(np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype= np.float32).itemsize)
# itemsize : 각 요소의 크기 출력

x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
print(x.shape)
# shape : 넘파이 배열의 크기 반환

print(x.reshape(-1,))
print(x)
# reshape : 배열의 구조 or Rank를 변경해주는 명령어, 배열 자체가 변경되지는 않음

x = np.array(range(8)).reshape(4, 2)
print(x)
# reshape를 쓸 때는 괄호 안의 값들의 곱이 요소의 개수와 맞아야 함 (-1 제외)

print(x.reshape(2, -1)) # 2 * 4
print(x.reshape(2, 2, -1))  # 2 * 2 * 2
# -1을 넣을 경우 자동으로 값을 정해줌

print(x.flatten())
# flatten : Rank가 2 이상인 배열을 1차원 벡터로 바꿔 반환, 배열 자체가 변경되지는 않음

# 배열 생성 함수

print(np.arange(-5, 5, 0.5))
# arange(a, b, c) : range와 같지만, 실수형도 포함 가능

print(np.ones(shape=(5, 2), dtype=np.int8))
print(np.zeros(shape=(2, 4), dtype=np.float32))
print(np.empty(shape=(3, 3), dtype=np.float64))
# ones, zeros : 배열 안의 값을 1, 0으로 채움
# empty : 활용 가능한 메모리 공간을 확보하여 반환
    # 해당 메모리 공간에 값이 남았을 경우 그 값을 함께 반환
        # 메모리를 초기화하지 않음! : 생성될 때마다 다른 값들이 반환
# ones, zeros, empty 모두 생성 시점에 dtype을 지정하면 해당 데이터 타입으로 배열 생성

x = np.arange(12).reshape(3, -1)
print(np.ones_like(x))
print(np.zeros_like(x))
print(np.empty_like(x))
# _like : 기존 넘파이 배열과 같은 크기로 만들어 내용을 1, 0, 빈상태로 만들어 줌

print(np.identity(n=4, dtype=int))
# identity : n * n 크기의 단위 행렬을 반환
print(np.eye(N=4, M=8, k=5))
# eye : N * M 크기의 행렬, 열을 기준으로 k 인덱스부터 숫자 1 생성, 반환값은 실수형태
print(np.diag(x, k=2))
# diag : 행렬에서 대각선에 있는 값들만 뽑아서 반환, 열 기준 k 인덱스부터 시작해서 오른쪽 아래로

print(np.random.uniform(0, 5, 10))
print(np.random.normal(0, 2, 10))
# random.uniform(시작값, 끝값, 데이터개수) : 균등분포
# random.normal(평균값, 분산, 데이터개수) : 정규분포
    # random이라 실행 결과는 매번 달라짐

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)
1 4
[[1 2 3]
 [4 5 6]]
4
(2, 4)
[1 2 5 8 1 2 5 8]
[[1 2 5 8]
 [1 2 5 8]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]
[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[            nan 0.00000000e+000 1.12544939e-311]
 [2.02369289e-320 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[2 7]
[4.44910643 1.0376149  1.96600354 0.11275858 0.97992642 1.74590176
 2.58193703 4.26610057 4.01950766 1.0043672 ]
[-0.75412792 -1.72196827  1.24251043 -2.03390168  1.95813475 -0.4110339