In [2]:
import numpy as np

# 연산 함수

test_array = np.arange(1, 13).reshape(3, -1)
test_array.sum()
# sum() : 요소들의 합 반환
test_array.sum(axis= 0) # axis = 0 : 행의 방향
test_array.sum(axis= 1) # axis = 1 : 열의 방향
# sum() 함수에서 axis로 2 이상의 rank에서 연산의 방향을 결정 가능

array([10, 26, 42])

In [8]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor
third_order_tensor.sum(axis= 0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [9]:
third_order_tensor.sum(axis= 1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [10]:
third_order_tensor.sum(axis= 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [11]:
# mean() : 평균 구하기
test_array.mean(axis= 1)

array([ 2.5,  6.5, 10.5])

In [12]:
# std() : 표준편차 구하기
test_array.std()

3.452052529534663

In [13]:
# std()도 axis를 사용하여 축을 기준으로 표준편차 구하기가 가능
test_array.std(axis= 1)

array([1.11803399, 1.11803399, 1.11803399])

In [14]:
# np.sqrt() : 각 요소에 제곱근 연산 수행
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [4]:
# 연결함수 : 두 객체간의 결합을 지원
    # 넘파이의 연결은 기본적으로 축을 기준으로 발생
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2)) # 괄호 하나 없앨 경우 'vstack() takes 1 positional argument but 2 were given'

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.hstack((v1, v2)) # 괄호 하나 없앨 경우 'hstack() takes 1 positional argument but 2 were given'

array([1, 2, 3, 4, 5, 6])

In [7]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [8]:
v2

array([[4],
       [5],
       [6]])

In [9]:
np.hstack((v1, v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
# 또 다른 연결 함수로 concatenate 함수가 있음
    # 축을 고려하여 두 개의 배열을 결합하는 역할
    # v, hstack과 다른 점은 concatenate는 생성될 배열, 사용되는 배열의 차원이 같아야 함
        # 두 개의 벡터를 2차원 배열로 결합하고 싶으면 벡터를 2차원으로 만든 뒤 함수를 사용해야함

v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1, v2), axis= 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
v1 = np.array([1, 2, 3, 4]).reshape(2, 2)
v2 = np.array([[5, 6]]).T   # T : 전치 배열로 변환할 때 사용하는 메소드
v1, v2

(array([[1, 2],
        [3, 4]]),
 array([[5],
        [6]]))

In [5]:
np.concatenate((v1, v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [6]:
# 사칙연산 함수
# 행렬의 크기가 같을 경우 기본적인 사칙연산이 가능함
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x + x, x - x, x / x, x * x, x ** x

(array([[ 2,  4,  6],
        [ 8, 10, 12]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[ 1,  4,  9],
        [16, 25, 36]]),
 array([[    1,     4,    27],
        [  256,  3125, 46656]]))

In [10]:
# 벡터의 내적 -> (m * n) dot (n * k) = (m * k)
x1 = np.arange(1, 7).reshape(2, 3)
x2 = np.arange(1, 7).reshape(3, 2)
x1, x2, x1.dot(x2)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[22, 28],
        [49, 64]]))

In [11]:
x2.dot(x1)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [13]:
# 브로드캐스팅 연산 : 하나의 행렬과 스칼라 값들 간의 연산 or 행렬과 벡터 간의 연산
    # 배열의 구조가 다른 배열간의 연산
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x + 10, x - 2, x // 3, x ** 2

(array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]]),
 array([[0, 0, 1],
        [1, 1, 2],
        [2, 2, 3]], dtype=int32),
 array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]))

In [15]:
x = np.arange(1, 13).reshape(4, 3)
v = np.arange(10, 40, 10)
x, v

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([10, 20, 30]))

In [16]:
x + v
# 브로드캐스팅 연산이 일어나면 뒤에 있는 벡터가 앞에 있는 행렬과 크기를 맞추려고 함
    # [10, 20, 30]의 벡터를 4 * 3의 행렬처럼 복제가 일어남

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [ ]:
# 넘파이의 장점 : C와 유사한 형태로 메모리를 관리하면서 C와 같은 연산 속도로 계산 가능
    # 파이썬에서는 리스트 간 연산에서 많은 시간이 걸리지만 넘파이는 이보다 빠른 연산 가능
        # 배열의 모든 요소들이 메모리 구조상 붙어있기 때문
# 넘파이는 파이썬의 가장 큰 특징인 동적 타이핑을 포기했지만, C로 구현되어 있어 배열 연산에 있어 성능정 우위 확보
# 연결 연산처럼 여러 배열을 붙이는 연산에서는 일반적인 리스트에 비해 속도가 느림
    # 메모리의 구조 때문